# Generated by Django 3.2.8 on 2021-10-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerNumber', models.CharField(max_length=60)),
                ('transactionID', models.IntegerField()),
                ('timestamp', models.DateField()),
                ('name', models.CharField(max_length=60)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStampDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('transaction_year', models.IntegerField()),
                ('transaction_month', models.IntegerField()),
                ('transaction_day', models.IntegerField()),
                ('transaction_hour', models.IntegerField()),
                ('transaction_minute', models.IntegerField()),
                ('transaction_week', models.IntegerField()),
                ('transaction_weekNum', models.IntegerField()),
            ],
        ),
    ]
